workflows:
  android-release:
    name: Build Android AAB
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build AAB
        script: flutter build appbundle

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
